### ISSUE TITLE
Check if categories are required for incidents

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1150]
We should be requiring at least one category on every incident, but we found a few incidents in the database with no category. Not sure if these are historical flukes or if we aren't requiring categories presently.

**Comment by chigby** [comment]
From what I can tell, we're requiring it via `min_num=1` on the InlinePanel for selecting categories here: https://github.com/freedomofpress/pressfreedomtracker.us/blob/828e56745b2d36ed8f0f80ba724576017fe01a59/incident/models/incident_page.py#L507

Though, as you've discovered, this is not a _particularly_ strong requirement and is not enforced everywhere.

**Comment by harrislapiroff** [comment]
Making a note here for myself: A number of assaults were published on Sep 28 and 29 without a category. Do some historical research to see if anything particular happened that day that would cause that to happen.

**Comment by chigby** [comment]
I wonder if it would be possible to hook up a nightly check to a management command? Writing a query to see if any incidents lack categories would be pretty straightforward. I'm just not sure how easy it would be to make that visible enough to be useful.

**Comment by harrislapiroff** [comment]
@chigby It's an interesting thought (especially since I have been writing a suite of similar [data integrity checks](https://observablehq.com/d/688adf80418b1f19)) but I guess for the purpose of this ticket I'm just interested in investigating if we can find an obvious way a content editor might be able to create an incident with no category.

**Comment by SaptakS** [comment]
As far as I can see, in pretty straightforward way using the UI, there seems to be no way to create incident without categories.
- If you try to publish an incident without filling the categories drop down, then it returns an error, since category name is required.
- If you delete the initial one incident categories form that's there, and try to publish, it still gives an error " Please submit at least 1 form. "

Given there is no restriction at database level, one can create programmatically for sure, but doesn't seem to be possible via Admin UI.

**Comment by harrislapiroff** [comment]
Closing this for now. Going to assume past issues with incidents with no category were flukes
