### ISSUE TITLE
Incident detail page blocks

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1186]
Incident pages will need Python code and templates for the following stream field block type:

- [x] Rich text ([Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A60362))
- [x] Pull quote (this is a quote displayed large, pulling a section of the text for visual interest, called "Inline quote" in [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A60362))
- [x] Block quote (this is a quote that is part of the text, indented and italicized, with an attribution. See example in this [Figma template](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3565%3A41473))
- [x] Image (called "Inline image" in [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A72698))
- [x] Twitter embed (called "Embed element" in [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3805%3A72698))
- [x] Video embed

Wherever possible we should reuse the existing stream field blocks with as few changes as possible (i.e., just writing a new template for an existing block type). Any that are changed should come with associated data migrations. Make a note of any existing blocks that don't fit in the above list and ask @harrislapiroff what to do with them.

**Comment by kevinhowbrook** [comment]
@harrislapiroff looking at the existing blocks https://github.com/freedomofpress/pressfreedomtracker.us/blob/1bf3ae596f39cb97f338f5a5ab48796481a2166a/incident/models/incident_page.py#L166-L179

We have code defining all these except the `Block quote` block.

We have extra blocks on the incident page body:
- Statistics
- Raw HTML
- Aliged, captioned image

So it looks like the tasks here are to update the existing blocks in your initial list and also define a new `Pull Quote` block.

For updating existing blocks, I've noticed that some are being used elsewhere eg the [video block](https://github.com/freedomofpress/pressfreedomtracker.us/blob/1bf3ae596f39cb97f338f5a5ab48796481a2166a/blog/models.py#L152) is used on the blog. If we are updating templates are we OK with the other models using these updated block templates too?

Thanks

**Comment by urlsangel** [comment]
Hi @harrislapiroff 

I've added templates and migrations for these template blocks, and requested your review on the PR: https://github.com/freedomofpress/pressfreedomtracker.us/pull/1205

Can you let me know if this is what you're after, as this is the first issue I've worked on for this project?

Also, the CI for this PR is failing, we think it's because IPython is failing a safety check - this is a bit out of my zone of knowledge, so it would be great if one of your team could look at it, or give me pointers on how to rectify the issue 👍

**Comment by urlsangel** [comment]
Hi @harrislapiroff 

I've added styles to most of the blocks referenced in this issue, with these exceptions:

- Video embed - _I can't find a design for this in Figma?_
- Statistics - _Not sure what to do with this one_
- Raw HTML - _Not sure what to do with this one_

Also, the rich text design in Figma doesn't have any links as a style guide reference - can this be added by the designer/owner of the file?

**Comment by harrislapiroff** [comment]
Video: Let's use the same design as for inline images, but a video embed where the image would be

Statistics can be ignored. We should probably remove that block at some point—I don't think we're using it.

Raw HTML: Fine to leave unstyled—just render it unescaped.

Links: See the [buttons](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=2710%3A22048) on the Figma. I think these might already be the default link styles, so it's possible no additional styling is needed there.

**Comment by urlsangel** [comment]
Hi @harrislapiroff 

I've just been reviewing this issue, and as far as I can tell all the required blocks are complete (I've checked them off in the list at the top of this issue).

The PR is blocked due to the safety check warning on `ipdb` - one of your team was going to look at this right?

There are also merge conflicts:

https://github.com/freedomofpress/pressfreedomtracker.us/pull/1205/conflicts

How do you normally resolve these, directly on Github, or locally? It would be great if I could understand your merging/rebasing workflow so that I can do the right thing 👍

**Comment by harrislapiroff** [comment]
@urlsangel We generally rebase branches onto the base branch locally before merging. Let me know if you have any issues or questions around that :)

**Comment by chigby** [comment]
Closed by #1232
