### ISSUE TITLE
Database page: Filters sidebar, basic

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1218]
Sidebar form for the database page. Use native HTML component instead of react/chart equivalents. Filters, for reference: [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=4008%3A76112)

**Comment by urlsangel** [comment]
Hi @harrislapiroff @chigby 

I've added Django forms to this implementation, and it's looking good for me locally.

The implementation I've used is:

- Added a [`FilterForm`](https://github.com/freedomofpress/pressfreedomtracker.us/pull/1228/files#diff-3cfd80c90fd47efbe1e425db6f5b1acfb67901a551c700260f96e3e7fc5a9f6bR6) class that enables dynamically adding forms based on the data from [`get_serialized_filters`](https://github.com/freedomofpress/pressfreedomtracker.us/blob/redesign/incident/utils/incident_filter.py#L522)
- Added a [`get_filter_forms`](https://github.com/freedomofpress/pressfreedomtracker.us/pull/1228/files#diff-3cfd80c90fd47efbe1e425db6f5b1acfb67901a551c700260f96e3e7fc5a9f6bR60) function to populate these forms (including the GET info from the request), add this to the[ index page context](https://github.com/freedomofpress/pressfreedomtracker.us/pull/1228/files#diff-3e5b35b8edb9410af29a5dcdc1da5cf800feae562abfe0a67b1dc634c7769766R208)
- Loop through the [forms and add their fields to the template](https://github.com/freedomofpress/pressfreedomtracker.us/pull/1228/files#diff-73397fb598e8702f2cceadd7e3d0ec9ed4d1813edd3298c3746b165e80e7f7d2R3) - as they are driven by the Django Forms API, they are correctly populated on page load with any values that are present in the query string

It appeared to me that items returned by `get_serialized_filters` that didn't have filter values were `categories`, so I've handled these separately by [making a `categories` filter item](https://github.com/freedomofpress/pressfreedomtracker.us/pull/1228/files#diff-3cfd80c90fd47efbe1e425db6f5b1acfb67901a551c700260f96e3e7fc5a9f6bR79) - this is filtering correctly for me locally, but it would be great if someone could confirm I've made the right assumption here?  

Also, the the items returned by `get_serialized_filters` that have a type of `radio` had no choices associated with the, but looking at the fields on the `IncidentPage` model, these all had choices of `MAYBE_BOOLEAN`, so this is what I've used.

This functionality is in the form initialisation though, so it feels a bit tightly coupled (what if you want a `radio` with different choices?) - I think it would be better if the choices for these `radio` fields were set at the serialization stage rather than the form stage?

I just need to write some tests to get the coverage back up to 100%, but other than that I think this will be ready for review.

**Comment by harrislapiroff** [comment]
This is done
