### ISSUE TITLE
Information on incident cards look cramped

### ISSUE THREAD

**Issue by SaptakS** [freedomofpress/pressfreedomtracker.us#1257]
![image](https://user-images.githubusercontent.com/9530293/156394241-27a2a190-d0be-415d-ad96-621ac538aa96.png)

As seen above, in smaller laptop screen (checked in 1280px width), the information on the incident cards look little cramped and wrapped. This is mainly in a 4 column grid. I don't know an exact solution for this. I wish container queries start getting adopted by all browsers very soon. This would be so much easier to address.

**Comment by harrislapiroff** [comment]
I think the font-size here might be a little larger than we're seeing in the mockups and that might make it work a little better. I'll look into this.

**Comment by chigby** [comment]
I wonder if part of the problem here is that the data rows are supposed to be aligned like that? Here's the home page from the Figma templates:

![image](https://user-images.githubusercontent.com/561931/157966963-86d1ee39-f7c2-4d60-92cd-e43f1ede7d09.png)

Note how the data table is not rendered in aligned columns, in contrast to @SaptakS's screenshot. Maybe that is contributing to the cramped feeling?
