### ISSUE TITLE
Category page charts

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1479]
Let's add the option to add charts to the category page as shown in Accurat's [Figma](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3584%3A55956):

![image](https://user-images.githubusercontent.com/296631/186477426-f515577d-5534-481b-b775-4f0b32dbd37d.png)

For now let's keep the implementation limited:

- [ ] Allow content editor to choose to show either a bar chart or no chart in the category page editing UI
- [ ] Aggregate bar chart by incidents
- [ ] Allow content editor to specify a date range to chart (as with the homepage charts)

But bear in mind these future requirements when implementing to make sure we can adapt to them easily ipn the future (if some of these are quick to do now, feel free):

- We will allow multiple types of charts eventually
- We may want to allow the content editor to choose to aggregate by number of targets or number of charges instead of number of incidents

**Comment by SaptakS** [comment]
@harrislapiroff in the date range, should it be just a year selector, or date selector? Because the chart in the screenhot has years in the x-axis unlike homepage which has months of each year. Putting a date selector is fine according to me, but if the range is very small (for example only 1.5 years) then the graph might not convey much information with only 2 bars.

**Comment by harrislapiroff** [comment]
@SaptakS That's a great point—let's just do a year selector if that's not too tricky.
