### ISSUE TITLE
Blog post templates

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1480]
Let's add the different templates for different blog post categories as documented in Accurat's Figma:

- [ ] [Newsletter](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3698%3A62440)
- [ ] [Special Section](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=3698%3A69119)

I leave it up to the implementer whether these should be implemented as separate page types or as a selection on the existing page type. Please review the mockups and write an architecture proposal as a comment on this ticket before beginning implementation.

A note:

- Newsletters should support rendering an interactive treemap with filters selected by the content editor as the lead graphic.
- However, the chart block type shown mid-article in the figma should be saved for another ticket.

**Comment by harrislapiroff** [comment]
Actually, after looking at this a little, I notice that specifying the chart at the top of the newsletter may be a bit complicated, so it's OK to implement the rest of this ticket without that first. I'm going to do some more thinking myself about the architecture there.

**Comment by SaptakS** [comment]
I think I would propose having them as a selection on the existing page type. I think editors are already used to adding newsletter as blog pages, so I think keeping the same flow is good. In fact there is not much difference between the newsletter and current blog template. The only differences are:
- Blog posts show a "In the Database" section, and newsletter don't. But right now, even in Blog posts we are not showing that.
- The CTA for blog posts is "Return to Blog" and for Newsletter is "Donate"
- The treemap which I think we can do as a separate PR.
- CTAs on top to subscribe and to visit archives

So I think the architecture we can have is :
- [x] Have 3 separate templates - `_default_blog.html`, `_newsletter.html`, `_special_blog.html`
- [x] Have a dropdown in admin to select the type of blog: Default, Newsletter, Special
- [x] Depending on the type selected by the editor, we chose in `blog_page.html` which of the 3 templates to include.
- [x] Default Blog:
  - [ ] Add the "In the Database" section to show the 4 latest incidents. (We can probably also allow the editor to curate these 4 incidents based on the content of the blog? Not sure if that will be too much extra work for the editors)
- [x] Newsletter:
  - [x] Copy almost same structure as `_default_blog`
  - [x] Replace "Return to Blog" CTA with "Donate" button
  - [x] Add "Go to archived editions" and "Sign up to the newsletter" CTA before the blog details table
  - [x] "Go to archived edition" button takes the user to the blog index page, filtered by `type=newsletter`
  - [x] "Sign up to the newsletter" button takes users to the standalone newsletter page
- [x] Special Blog
  - [x] Copy the same structure as `_default_blog` apart from the header part
  - [x] Use the `lead_image` for the blog as the hero image background. 


**Few questions that I have:**
- Newsletters have right now don't have any headings or other structures much. In the design it's proposed a "Feedback & Your Support" section. Should I leave it to the editors to structure it that way in the newsletter body? Or should I enforce a separate section in the admin? In either case, there will be a little discrepancy between old newsletters and the new ones.
- The newsletter design has a "Read incidents" section in between the body. Not sure if we are to implement that and if anyone has any suggestions how. I could think of providing a separate block with incident choosers which the editors can then decide if they want and where they want.
- For the Special blog, I am little worried about the color contrast. Since the navigations are in black but the title of the blog and credits are in white, the image always needs to be of the format that the top of the image is light and bottom is dark. Else we will have a color contrast issue. I can add a black gradient to ensure the bottom is always darker, but still not sure with having the navigations in black.

cc @harrislapiroff

**Comment by harrislapiroff** [comment]
> In the design it's proposed a "Feedback & Your Support" section. Should I leave it to the editors to structure it that way in the newsletter body? Or should I enforce a separate section in the admin?

Let's leave it to the admins

> The newsletter design has a "Read incidents" section in between the body. Not sure if we are to implement that and if anyone has any suggestions how.

Let's go more generic. "Read incidents" should be implemented as a heading block of some appropriate level, I think, and the buttons should be a generic "button block" that can support a link to a page or URL

> For the Special blog, I am little worried about the color contrast. Since the navigations are in black but the title of the blog and credits are in white, the image always needs to be of the format that the top of the image is light and bottom is dark. 

As discussed in web sync, let's implement this as is and then start playing with accessibility options. I could imaging some tools to swap between black and white for the colors or add or remove background gradients. Ideally this would happen automatically based on image contrast, but in practice we may have to make these manual flags.

This proposal looks good otherwise!
