### ISSUE TITLE
Improved tag multiple-selection

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1482]
It seems like we're delaying further work on the database filter interface at least a bit. PFT editors report that being able to filter by multiple tags at once more easily would dramatically improve *their* user experience (in addition to likely improving the experience for site visitors some amount).

Let's add in a better interface as easily as we can bearing in mind that it may well be an interim solution. I leave specifics to the implementer:

- Something similar to the autocomplete interface we had for the previous design would be acceptable.
- If it seems easy enough to implement something similar to what's in the [mockup](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=4330%3A93822), go for that (the mockup seems to show tags as radio buttons though—we will need them as checkboxes)

Please write a comment on this ticket with your proposed architecture before beginning work on it.

**Comment by chigby** [comment]
The mockup: 
![image](https://user-images.githubusercontent.com/561931/194160465-820f90cf-3275-4514-992e-6164c479797a.png)

[See also](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=4243%3A84279)

**Comment by chigby** [comment]
I feel like the shortest path to something that allows multi-selections in a user-friendly way is to grab something "off-the-shelf" like [react-select](https://react-select.com/home) which basically mimics the wagtail-autocomplete UI of old (but without directly using any of its code). The component in the mockup I think has a lot going on that we would either have to ignore or come up with a strategy for that ideally would work when extended to all the filter components. We will have to do this eventually, but it's definitely going to be some work up-front to determine the count of all the tags that match the current filters (which as of now do not actually match the displayed incidents!).

It's also not clear what exactly happens when I start using the "Find tags..." text input. I tried to find it in Figma but was unable. I guess it would display an autocomplete-type list that when you make a selection gets, like, added to the visible 3 tags as another check box, maybe? Does this change if "see complete list" is active? These questions would need at least preliminary answers before we go for the Figma design, I think.

**Comment by chigby** [comment]
I'm thinking the most prudent thing here is to adapt the multi-radio setup that Accurat made for the `StateFilter` component in the charts code. Screenshot:

![image](https://user-images.githubusercontent.com/561931/194412995-8706def6-ca99-44f4-bb8d-18398d881fb3.png)

I think I can change this to a checkbox list, limit the initial tags to 3, and add a "see complete list" control that opens it out to all the tags. "Find tags..." I think ought to wait until we've spec'd that out more completely.
