### ISSUE TITLE
Subpoena metadata changes

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1512]
Very similar to arrest metadata changes. [Spec out more soon]

**Comment by chigby** [comment]
[Notes from spec meeting](https://docs.google.com/document/d/1OLYe27H2_OvmJoEtpjuU1hEiYglaD36ZofNUMAgTI-s/edit#)

Part of #1478

**Comment by chigby** [comment]
Some examples of how the information could be presented on the incident detail page and cards:

**An incident with a 3rd party target:**

![image](https://user-images.githubusercontent.com/561931/218867759-e26a86d4-341f-4310-af8e-5f2162a9c346.png)


**An incident with a journalist target and several legal orders**
![image](https://user-images.githubusercontent.com/561931/218867445-d7995c7c-7a02-43bd-8dac-9803e83e9697.png)

My goal here is to try and compress the information so that it doesn't require, like, subfields (i.e. each legal order having its own "Field Name: Value" listing). Looking at this, it does kind of seem like "Other" by itself is kind of problematic without context. Maybe needs to be changed to "Other information" and "Other legal order" or something.
