### ISSUE TITLE
Change homepage chart colors

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1598]
One source of confusion that we've observed with users is around the color on the homepage charts:

![image](https://user-images.githubusercontent.com/296631/226468273-f43cfaab-7dfb-448f-aa3b-8e5d4b722e57.png)

In the treemap on the left, orange represents the assaults category. But on the center and right it represents all incidents. Sometimes users get confused and think it represents only assaults across all three charts.

This ticket is to develop and implement a way of handling colors in these charts that avoids this confusion (e.g., by making the map and bar charts B&W or by removing orange from the treemap).

You can review the charts color palette in this [Figma document](https://www.figma.com/file/H3uTXxT88ofhdebUFgzEo9/PFT-%E2%80%93-Hand-off-Guide?node-id=1893-9644&t=eKBR6PpiYEMvkInA-4) provided to us by the designers. This color palette is a guideline, not a rule—if your design solution introduces a new color, that should be fine, as long as it looks good.

**Comment by dkaoster** [comment]
Spent some time with this today, and went ahead and tried both options that @harrislapiroff mentioned.

By simply changing the color of the "assault" category, the visualization is already less confusing:
![Screenshot 2023-03-21 at 2 26 40 PM](https://user-images.githubusercontent.com/3477162/226745410-a2fd4332-2dc7-4d8f-be9f-c319956af5d7.png)

However, I fear that because the visualizations are so close to each other, users may still treat the treemap as a "legend" and look for the orange represented in the map and bar chart in the treemap. So, by making the map and the bar chart gray with a black hover state, we get the following:
![Screenshot 2023-03-21 at 2 22 08 PM](https://user-images.githubusercontent.com/3477162/226745706-76ec9a90-816a-4856-92be-8703922be6f5.png)

I do believe that this is more clear, although the drawback is that we lose the splash of color across the whole visualization. If we wanted to retain color in a way that is uniform across all three visualizations, one potential option would be change the circles in the map to a pie chart breaking down the categories and the bar chart into a stacked bar chart, but I do fear that may make it more complex than a simple "at a glance" chart that this seems to be focused toward.

Thus, my recommendation would be to simply make the map and bar chart gray.

Thoughts?

**Comment by harrislapiroff** [comment]
After discussing with @eloquence and @KAMcCudden in Slack, let's go with the color version.
