### ISSUE TITLE
Download charts as images

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1609]
Blocked by #1608 

Add a button to charts that allows users to download them as high quality images. These images should include "Source: U.S. Press Freedom Tracker (pressfreedomtracker.us)" rendered within the image. Possibly this credit should be customizable (attn @KAMcCudden)

This is a feature that tracker editors will use themselves—currently they embed a lot of screenshots of charts in newsletters, tweets, etc. This will allow them to generate images with more consistent quality.

This is also a feature that will benefit the tracker by ensuring that when third-party publications reshare tracker charts it includes a credit that leads back to us.

**Comment by KAMcCudden** [comment]
@harrislapiroff this source line looks great to me. I would say we can skip custom-ability, even, as this is solid branding, since would all be pulled from the data (eg no need to name someone, as in your custom works). tho if want to play with designs for source line around words v. avatar v image plus avatar happy to give opinion

![Avatar_yellow](https://user-images.githubusercontent.com/46460749/229126204-8fcafe27-1db0-4efc-8e06-ec24d4eeb5ac.png)

![Avatar_white](https://user-images.githubusercontent.com/46460749/229126226-ee8411f0-458f-41d3-9485-395fb6fa86a8.png)
