### ISSUE TITLE
Treemap won't render without a category

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1656]
I can't seem to get a treemap to render if I don't choose some categories for it. We should make it render with a dataset including all categories if no categories are selected.

I also think the treemap category chooser could be improved UX-wise. I know they're pages but I wonder if we could use a multi-autocomplete field or checkboxes for it instead of a page chooser? Feel free to split into a separate ticket if it's too hard to do both at once.

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/9b990c42-abc9-4037-aaad-4e2063d1ea9d)

**Comment by dkaoster** [comment]
> I also think the treemap category chooser could be improved UX-wise. I know they're pages but I wonder if we could use a multi-autocomplete field or checkboxes for it instead of a page chooser? Feel free to split into a separate ticket if it's too hard to do both at once.

I think this would be a great feature, although I'm not quite sure where to start implementing this. I went with `PageChooserBlock` because that's how @chigby had it originally set up when we did the first bar chart visualization, but let me know if you have any pointers or things I can look at to save some time building this out.

**Comment by chigby** [comment]
Does wagtail autocomplete support blocks? Possibly related to https://github.com/wagtail/wagtail-autocomplete/issues/148

Because categories are ultimately a type of page, it is nice to be able to choose the actual page, but since they don't change that often, I could see re-working the chooser here as a choice field, where you are choosing category names, and I think we do have a `CheckboxMultipleChoice` multiple choice widget somewhere in the code that does allow choosing multiple values via checkboxes.

One thing I am noticing here on your screenshot is that the help text is repeated, which I think actually is a mistake on my part: the `help_text` for the `categories` field ought to be on the `ListBlock` (where it will appear once for the whole list), rather than the `PageChooserBlock` (where it appears for every page choice) -- whoops!

**Comment by harrislapiroff** [comment]
If we can make checkboxes work, that would be great. I think the significant thing to an editor is the name of the categories, not where they’re found in the page tree, so I think that just adds extra steps. If it turns out to be complicated to implement, we can skip it though, once the bug is fixed. I do expect the most common behaviors will be to select one or zero categories, so this widget is still easy enough for those cases.

**Comment by chigby** [comment]
https://github.com/freedomofpress/pressfreedomtracker.us/pull/1661 -- Draft PR with what block/model changes for this would look like

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/561931/17017292-c7d3-405e-8342-731d352390df)

**Comment by dkaoster** [comment]
Why don't I separate the bug fixes from the UX improvements then, I think I have the bug figured out.

**Comment by chigby** [comment]
That sounds great. I made the PR because I wasn't sure how we'd want to combine efforts here but that makes sense.

**Comment by harrislapiroff** [comment]
@chigby Those checkboxes look much better to my eye. I think the help text could use a bit of work. I'd propose: "If selected, incidents belonging to any of the selected categories will be included," but feel free to modify
