### ISSUE TITLE
Prerender and pregenerate charts for "primary image"

### ISSUE THREAD

**Issue by dkaoster** [freedomofpress/pressfreedomtracker.us#1668]
Related to #1658, we'd like to explore methods for rendering charts to html and static images.

## The Problem(s)
The reason for doing this is two-fold. As can be seen in #1658, we would it to be possible to set the chart as the primary image of a blog post. While there is currently code to generate the interactive version of these charts, they are all written in client-side React, which means that they only get loaded after the page loads. (and they don't load at all for folks with javascript disabled)

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/b6cbcd80-c726-4bf3-bbe0-6f04426c69c3)

The second problem lies in the "meta-image", or the image that gets shared to social media sites and search engines as the promotional image for a blog post. If we were to use this chart as a primary image, the chart should also be the promotional image for the blog post, as the mocks show below.

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/57722231-d676-45e8-92c7-dd9706186b94)

Unfortunately, this would require for the image to be hosted on a URL somewhere for the image to be properly linked to.

## The Proposal(s)

The proposal is to spin up a lambda service running node.js that can generate both the SVG chart to put in the large primary image slot on blog pages, as well as render the SVG chart as a png / jpg. Both of these could then be stored on an S3 bucket and then linked to directly in the html. Then, whenever a new blog post is published in wagtail, wagtail could simply spin up this lambda service to generate these assets and store them in S3. This way, the service only runs when it is needed, and isn't in the line of requests blocking a user's page load of a blog post.

**Comment by harrislapiroff** [comment]
@dkaoster Is there some sort of ready-made service we can deploy for this or would this involve us writing our own node service to do this rendering?

**Comment by dkaoster** [comment]
There isn't as far as I'm aware, but there are a lot of libraries that would be easy enough to assemble together and the boilerplate code for the service could be less than a couple hundred lines. Something like:

- [Express.js](https://www.npmjs.com/package/express) for handling incoming requests
- [Canvg](https://www.npmjs.com/package/canvg) for rendering svgs to a canvas
- Some method for rendering react components to SVGs (this way we can simply reuse most of the chart code already written)
- [AWS SDK](https://www.npmjs.com/package/aws-sdk) for getting files onto s3

**Comment by harrislapiroff** [comment]
Looks like [renderToString](https://react.dev/reference/react-dom/server/renderToString) is React's native solution for the third bullet there

**Comment by eloquence** [comment]
@harrislapiroff @dkaoster 

To clearly scope this issue, I think we need to more precisely define the desired behavior of the charts for the newsletter (I did read the spec in #1658):

- Are these always charts of the  "total incidents YTD" type? If so, do we have/need a means for an editor to specify the date range of the chart?
- What level of interactivity do we want for the simplified charts?
  - on the blog post
  - in the index
- Do the interactive versions of the charts query the live API, or do they use a cached snapshot of the data?
- Do the totals need to be updated if an incident gets backdated at a later time?

I think the implementation story may be a lot more straightforward if we treat them as snapshot charts rather than live charts, and limit interactivity on both pages to stuff like tooltips -- in that case, re-generating a snapshot would update also all pre-generated copies of it. 

With the defined behavior in mind, this looks like a potential infra/web collaboration to ensure that the service we build meets those requirements in terms of generated assets & their invalidation.
