### ISSUE TITLE
Experimental deployment not showing the latest changes

### ISSUE THREAD

**Issue by soleilera** [freedomofpress/pressfreedomtracker.us#1795]
# Description

Experimental deployment for node service pre-generated chart feature not showing the latest code changes.

**Comment by harrislapiroff** [comment]
@maeve-fpf reports the error in the logs for the node service is

```
+ npm run start

> chart_pregenerator@0.0.0 start
> node ./build/server.js

npm ERR! code EROFS
npm ERR! syscall open
npm ERR! path /home/pft_node/.npm/_cacache/tmp/b8cab16d
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, open '/home/pft_node/.npm/_cacache/tmp/b8cab16d'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! Log files were not written due to an error writing to the directory: /home/pft_node/.npm/_logs
npm ERR! You can rerun the command with `--loglevel=verbose` to see the logs in your terminal
```

Looks like we need to update the node service docker file or startup script to work on a read-only filesystem. @chigby I think maybe this task is best suited for you?

***

@maeve-fpf reports the error in the logs for the django service is

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.DuplicateTable: relation "common_chartsnapshot" already exists
```

To my eye this looks like a migration issue somehow. Either there are duplicate migrations in the code or the experimental DB somehow got out of sync with its code.

**Comment by soleilera** [comment]
This is not "blocked" but "slowed down" by https://github.com/freedomofpress/infrastructure/issues/4468

**Comment by chigby** [comment]
I guess I'm not completely sure how to approach this problem. So we're running the chart service on a read-only filesystem. Can we apply this configuration to the development environment so it can be tested there? Is it a matter of updating something in `docker-compose.yaml` (or the production equivalent)? I tried changing some of the volume permissions for the node-chart-pregenerator service but it didn't appear to reproduce the `EROFS` error--it still worked, actually. Without knowing more about the environment and/or build procedure that's running into problems, I'm feeling a little lacking in information to proceed.

**Comment by maeve-fpf** [comment]
I believe you want to specify `read_only: true` in docker-compose.yml for the root volume.

**Comment by chigby** [comment]
Huh! That's pretty close to what I did try, which was changing the `node-chart-pregenerator` service to have:

```yaml
    volumes:
      - ./:/django:ro
```

and 

```yaml
    environment:
      DEPLOY_ENV: production
```

But when I did that, the service started without any errors.

**Comment by chigby** [comment]
It also starts without errors for me using the more verbose syntax:

```yaml
  node-chart-pregenerator:
    # ...
    volumes:
      - type: bind
        source: ./
        target: /django
        read_only: true
    environment:
      # ...
      DEPLOY_ENV: production

```

**Comment by chigby** [comment]
Oh, maybe that read only is not in the right place. I thought I tried `read_only` at the service-level yesterday and docker compose rejected it, but [the docs](https://docs.docker.com/compose/compose-file/05-services/#read_only) do say it ought to work.

**Comment by chigby** [comment]
Having looked into this some more, I am starting to think that in development mode, the current setup of the chart pregenerator is not compatible with a read only file system. Because ultimately what we are doing there is running `esbuild` to compile our JS source files, which outputs a file (right now it's `build/server.js`) and running that file enables the server. And with a read-only file system, writing the file won't work.

It feels like it would be possible to work around this in production, since could could compile the JS with `esbuild` only once as part of the container build step, but in development mode one thing we need is to re-build the server code if one of the source files changes. Right now I'm not totally sure how to get around this without taking a step back and thinking about our architecture.

@dkaoster @harrislapiroff Let me know if you have thoughts about this, or if you think my understanding of how the current system works is incorrect (it might be!). 

But right now, if we want to keep this component on a read-only filesystem, we might need to think about outputting the `server.js` code somewhere else that _is_ writable, or using something besides `esbuild` that supports, like, in-memory compiling and running (something I haven't looked into at all!)

**Comment by harrislapiroff** [comment]
@chigby This seems very analagous to how our webpack container works, now? Can we mimic that setup?

OTOH why do we need a compilation step for server code regardless? Is there an option of running `esbuild` at runtime? (Actually, now that we're talking about, what is esbuild getting us over vanilla node? Not that I want us to restructure the PR at this juncture, but I just realized I don't actually know why we're using it here.)

**Comment by dkaoster** [comment]
@harrislapiroff Because the chart-pregenerator server is rendering react components that are written as jsx files, we need some kind of compilation step to at the very least get those jsx files compiled into something node can work with. 

We have to go with esbuild over something like webpack or vite because of the way that our project is structured with the react components for the charts (ie bar chart, treemap chart, map) being shared from outside of the chart-pregenerator source itself. I'm sure someone could probably figure out a way to get this structure to work with webpack, but I spent a long time fiddling with it and could really only get it to work easily with esbuild.

@chigby That makes sense to me. I think ideally we would build it once during the container build step and not have production rebuild it when it spins up.

**Comment by harrislapiroff** [comment]
OH right, I forgot about JSX 🤦‍♀️ . Okay, that makes sense! Okay, then that just leaves my questions about runtime transpilation or mimicking the webpack container setup.

**Comment by chigby** [comment]
The webpack container does not use a read-only filesystem, so that's one difference.

**Comment by harrislapiroff** [comment]
@chigby Right, but how does it work on prod?

**Comment by soleilera** [comment]
Main issue is resolved but we are still troubleshooting remaining issues on the current branch.
