### ISSUE TITLE
Smart Search Phase One (Part II)

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#1801]
I think there was a bit of missed communication on my part in the implementation of smart search phase one. @dkaoster rigged it up so that it always displays the most frequently used tags, but we actually want it to display the tags selected in the admin if there are any.

![image](https://github.com/freedomofpress/pressfreedomtracker.us/assets/296631/28c18437-b1dc-4233-b4ed-903bf8ea4957)

**Comment by harrislapiroff** [comment]
(The smart search looks super slick otherwise! Just want to make sure we're not forever showing this very similar very constant list of tags 😅 )

**Comment by dkaoster** [comment]
Should I revert the last one and make changes? or just do this in a follow up?

**Comment by harrislapiroff** [comment]
@dkaoster Just do it as a follow up! But if we can get it merged before deploy time this week, that would be amazing. I'm hoping it won't be too intensive of a change (famous last words, I know)

**Comment by dkaoster** [comment]
@harrislapiroff Question for you: on the homepage, it's easy enough to read the `data_viz_tags_json` as it is easily accessible from the page. 

![Screenshot 2023-11-27 at 5 05 44 PM](https://github.com/freedomofpress/pressfreedomtracker.us/assets/3477162/d6b5b5a8-c556-4492-8232-2c205e649b87)

However, on the search bar in the incidents database page, the `data_viz_tags_json` isn't passed over from the homepage into the template for this page, so the easiest thing to do would be for this page to show the most frequently used tags.

![Screenshot 2023-11-27 at 5 06 03 PM](https://github.com/freedomofpress/pressfreedomtracker.us/assets/3477162/7d5a0da3-bf90-4eff-b15b-16c4828201f6)

Is this the expected behavior? Or would you like the incidents database page to also show the same tags that are shown on the homepage?

**Comment by harrislapiroff** [comment]
@dkaoster Good catch. I think this is one thing Accurat's designs simply don't account for. Since this is really just an intermediate phase, we don't need a high level of polish and consistency. Let's leave it as "frequently used tags" on the search page.

Actually since the label is "Trending Topics" maybe we can update it to do frequently used tags from the past year, if that's not too challenging? I'm ok with just updating the `chooseMostFrequentTags` function to a `chooseTrendingTags` function or something.

**Comment by dkaoster** [comment]
Not sure if my understanding is correct, @harrislapiroff can you double check here to help me confirm? https://github.com/freedomofpress/pressfreedomtracker.us/pull/1803
