### ISSUE TITLE
Unable to add "arresting authority"

### ISSUE THREAD

**Issue by sophieongithub** [freedomofpress/pressfreedomtracker.us#1857]
I went to add text to the "arresting authority" box in the arrest metadata and I'm getting this error: "Failed to create new item."
![Screenshot 2024-04-25 at 4 43 39 PM](https://github.com/freedomofpress/pressfreedomtracker.us/assets/87768517/634985a8-4c16-451e-a6c4-af3d67c2ef02)

**Comment by chigby** [comment]
Pretty sure this is due to a lack of permission to create Law enforcement organization items. See [this entry](https://logs.freedom.press/app/discover#/doc/filebeat-*/filebeat-gke-2024.04.25?id=biAUF48B_SahYj2jZriA) in the logs. Recommended fix: add these permissions to the editors group (and any other groups that need it).

The result should look like this: 
<img width="627" alt="image" src="https://github.com/freedomofpress/pressfreedomtracker.us/assets/561931/f8042cf8-bef4-4d72-b926-eb0f67d84964">

**Comment by chigby** [comment]
@sophieongithub Has this been resolved? Do you have the right permissions now?

**Comment by sophieongithub** [comment]
Requested perms changes from infra [here](https://github.com/freedomofpress/office-internal/issues/604), but looks like we can take care of PFT ourselves b/c we already have two admin team members - will update here when that's done

**Comment by sophieongithub** [comment]
@chigby this is all set

**Comment by chigby** [comment]
Great! Closing this issue.
