### ISSUE TITLE
Embedded video showing up tiny

### ISSUE THREAD

**Issue by sophieongithub** [freedomofpress/pressfreedomtracker.us#1880]
Hi team! We tried to embed a video in a Tracker incident and while marked as "full width", it showed up very small. Possible to fix this so it takes up the full width of the text columns? Thank you!
How it looks on the back end:
![Screenshot 2024-07-16 at 3 51 02 PM](https://github.com/user-attachments/assets/6902eefd-b60b-4742-a78c-344fc7565666)
How it looks in the preview:
![Screenshot 2024-07-16 at 3 50 50 PM](https://github.com/user-attachments/assets/d579fc86-c70e-4ed8-9db6-ae5e73cb0c20)

**Comment by chigby** [comment]
Did some troubleshooting here: the size of the embed is partially determined when it's fetched from the media provider. The result is we're sent an `iframe` that has fixed height and width attributes. This is a little awkward since our layout is somewhat flexible in terms of how wide the article body column can be. I've corrected some of this by adding a `max_height` and `max_width` argument to the embed definition here: 

https://github.com/freedomofpress/pressfreedomtracker.us/blob/develop/common/blocks.py#L118

But I don't know if this is the best thing to do universally. @SaptakS any ideas?

**Comment by harrislapiroff** [comment]
Worth seeing if this approach fixes it https://github.com/freedomofpress/freedom.press/pull/1403

**Comment by chigby** [comment]
Fixed by  #1882
