### ISSUE TITLE
Replace RawHTMLBlocks used for tweet embedding with TweetEmbedBlocks

### ISSUE THREAD

**Issue by harrislapiroff** [freedomofpress/pressfreedomtracker.us#808]
This is a content issue, but could be aided by a programming solution (for instance, auto-identifying which incidents and articles are using RawHTMLBlocks).

Peter was using RawHTMLBlocks to embed tweets using code provided by Twitter. With #805 we now have a first-class way of embedding tweets. We should switch historical uses of RawHTMLBlock out to use that instead.

- [x] Reinstall Wagtail Inventory (if incompatibility is resolved)
- [ ] Use WI to find articles with RawHTMLBlocks and generate a list
- [ ] Make a process for updating all those articles

**Comment by chigby** [comment]
Additionally, we would like to use wagtail-inventory to:

- [x] Look for `IncidentPages` with `image` blocks in the body
- [x] ~Update those pages to use `AlignedCaptionedImageBlock` instead.~

(final bullet point moved to #1003)

**Comment by chigby** [comment]
`RawHTMLBlock`: 94 matches
![image](https://user-images.githubusercontent.com/561931/105081533-525b2f80-5a60-11eb-9485-05c0c54931f5.png)

`ImageChooserBlock`: 40 matches
![image](https://user-images.githubusercontent.com/561931/105081605-64d56900-5a60-11eb-8430-f5ec61b677eb.png)

**Comment by eloquence** [comment]
Discussed at web sync today; we'll need to do some research into:
- the behavior of Wagtail's tweet embedding feature when tweets are deleted
- any other solutions that people have used to deletion-proof tweet embeds.

Currently, deleted tweets that were saved as raw HTML blocks will show the original text as plaintext as a fallback, because it is part of the HTML. We'll want to make sure that we don't lose this content as part of any migration.

**Comment by chigby** [comment]
According to [the docs](https://docs.wagtail.io/en/v2.7.1/advanced_topics/embeds.html#wagtail.embeds.models.Embed):

> Embeds are fetched only once and stored in the database so subsequent requests for an individual embed do not hit the embed finders again.

From looking in [the code](https://github.com/wagtail/wagtail/blob/v2.11.3/wagtail/embeds/embeds.py), I couldn't find anything that indicated the embeds would be invalidated after some kind of trigger, time-based or otherwise.

**Comment by harrislapiroff** [comment]
This is good. It means our embeds are roughly deletion-proof—assuming the embed provider includes an HTML fallback in their embed code, which Twitter does. So if we did want to convert old embeds, we could create rows in the embed table directly that contained the migrated embed HTML and bypass validation. Not 100% sure this is worth it still, but it's a thought.

**Comment by eloquence** [comment]
How would we handle e.g. Trump tweets in that scenario?

**Comment by harrislapiroff** [comment]
@eloquence The HTML in the raw html field _is_ the embed code from the time the tweet was embedded. We would just copy that straight over into the database for embeds. And it includes a fallback that displays the tweet as plain-text if the tweet fails to load. Meaning, visually, there would be no change on the frontend.

**Comment by eloquence** [comment]
Upon discussion and investigation, we've agreed that there's limited benefit and some potential risk in migrating historical content. Legacy HTML blocks should fall back nicely if the tweet is no longer available. Closing this issue.
